---
  - name: add key
    apt_key: keyserver=keyserver.ubuntu.com id=EA312927

  - name: add repository
    apt_repository: repo="deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse"

  - name: install
    apt: name=mongodb-org state=present update_cache=yes
