---
  - name: Add apt key
    apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

  - name: Add repository
    apt_repository: repo='deb https://deb.nodesource.com/node_4.x trusty main'

  - name: Ensure Node.js and npm are installed.
    apt: "name=nodejs state=present update_cache=yes"

  - name: Install global npm tools like bower, gulp, pm2 ...
    npm: name={{ item }} global=yes registry=https://registry.npm.taobao.org
    with_items:
      - bower
      - gulp
      - cnpm
      - webpack
      - browserify
      - pm2
      - grunt-cli
