---
  - name: Add apt key
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

  - name: Add repository
    apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'

  - name: Install postgresql
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - postgresql-9.5
      - postgresql-client-9.5
      - postgresql-9.5-postgis-2.2
      - postgresql-9.5-postgis-scripts
